graph TD
    Start( )
    style Start stroke:#000,stroke-width:2px,fill:#000,color:#fff;
    End( )
    style End fill:#fff,stroke:#000,stroke-width:2px;
    fork1@{shape: fork}
    join1@{shape: join}

    %% Flow
    Start --> fork1

    %% Branch 1: Database Preparation
    fork1 --> A[Load DB Configuration]
    A -- "[DB Credentials]" --> B[Establish DB Connection]
    
    %% Branch 2: Data Processing
    fork1 --> C[Load Election Results Data into DataFrame]
    
    %% Aggregation check
    C -- "[elec_results_df:DataFrame]" --> D{"Decision [Data at EAVS level?]"}
    D -- "[No]" --> E[Aggregate precinct data to EAVS level]
    E -- "[agg_elec_results_df:DataFrame]" --> F[Load EAVS Geounit Data into DataFrame]
    D -- "[Yes]" --> F
    
    %% Main processing steps
    F -- "[geounit_df:DataFrame]" --> G[Create EAVS Lookup Map]
    G -- "[lookup_map:dict]" --> H[Map Counties in Results DataFrame to EAVS Geounit Codes]
    H -- "[mapped_elec_results_df:DataFrame]" --> I[Calculate and Print R/D Vote Split Information]
    I --> J[Format Data for Database]
    
    %% Join branches
    B -- "[DB Engine]" --> join1
    J -- "[formatted_elec_results_df:DataFrame]" --> join1

    %% Final Step
    join1 --> K[Write Election Results to Database]
    K --> End
