import type { BubbleChartDataPoint } from "./BubbleChart";

export const dropBoxData: BubbleChartDataPoint[] = [
  { name: "Oklahoma County", xValue: 63, yValue: 6.8, size: 8, party: "Rep" },
  { name: "Tulsa County", xValue: 65, yValue: 4.2, size: 7, party: "Rep" },
  { name: "Cleveland County", xValue: 59, yValue: 5.9, size: 6, party: "Rep" },
  { name: "Canadian County", xValue: 73, yValue: 3.4, size: 5, party: "Rep" },
  { name: "Payne County", xValue: 61, yValue: 7.3, size: 6, party: "Rep" },
  { name: "Comanche County", xValue: 68, yValue: 4.6, size: 6, party: "Rep" },
  { name: "Pottawatomie County", xValue: 76, yValue: 2.2, size: 4, party: "Rep" },
  { name: "Grady County", xValue: 71, yValue: 3.1, size: 5, party: "Rep" },
  { name: "Muskogee County", xValue: 64, yValue: 5.4, size: 5, party: "Rep" },
  { name: "Garfield County", xValue: 67, yValue: 3.7, size: 4, party: "Rep" },
  { name: "Kings County", xValue: 21, yValue: 17.6, size: 10, party: "Dem" },
  { name: "Queens County", xValue: 29, yValue: 14.9, size: 9, party: "Dem" },
  { name: "New York County", xValue: 18, yValue: 19.2, size: 10, party: "Dem" },
  { name: "Bronx County", xValue: 13, yValue: 18.5, size: 9, party: "Dem" },
  { name: "Richmond County", xValue: 39, yValue: 12.1, size: 8, party: "Dem" },
  { name: "Westchester County", xValue: 34, yValue: 13.9, size: 8, party: "Dem" },
  { name: "Nassau County", xValue: 43, yValue: 9.7, size: 8, party: "Dem" },
  { name: "Suffolk County", xValue: 46, yValue: 10.6, size: 8, party: "Dem" },
  { name: "Erie County", xValue: 37, yValue: 11.5, size: 7, party: "Dem" },
  { name: "Monroe County", xValue: 35, yValue: 10.9, size: 7, party: "Dem" },
];

export const equipmentQualityData: BubbleChartDataPoint[] = [
  { name: "Kings County", xValue: 20, yValue: 95, size: 10, party: "Dem" },
  { name: "Queens County", xValue: 24, yValue: 88, size: 9, party: "Dem" },
  { name: "New York County", xValue: 28, yValue: 105, size: 10, party: "Dem" },
  { name: "Bronx County", xValue: 32, yValue: 79, size: 9, party: "Dem" },
  { name: "Richmond County", xValue: 36, yValue: 92, size: 8, party: "Dem" },
  { name: "Westchester County", xValue: 40, yValue: 81, size: 8, party: "Dem" },
  { name: "Nassau County", xValue: 44, yValue: 90, size: 8, party: "Dem" },
  { name: "Suffolk County", xValue: 48, yValue: 72, size: 8, party: "Dem" },
  { name: "Erie County", xValue: 52, yValue: 88, size: 7, party: "Dem" },
  { name: "Monroe County", xValue: 56, yValue: 70, size: 7, party: "Dem" },
  { name: "Onondaga County", xValue: 60, yValue: 79, size: 6, party: "Dem" },
  { name: "Orange County", xValue: 64, yValue: 65, size: 5, party: "Dem" },
  { name: "Rockland County", xValue: 68, yValue: 72, size: 6, party: "Dem" },
  { name: "Albany County", xValue: 72, yValue: 60, size: 5, party: "Dem" },
  { name: "Dutchess County", xValue: 76, yValue: 55, size: 4, party: "Dem" },
  { name: "Oneida County", xValue: 80, yValue: 62, size: 4, party: "Dem" },
  { name: "Ulster County", xValue: 84, yValue: 48, size: 5, party: "Dem" },
  { name: "Broome County", xValue: 88, yValue: 53, size: 4, party: "Dem" },
  { name: "Chautauqua County", xValue: 30, yValue: 92, size: 3, party: "Dem" },
  { name: "Chemung County", xValue: 35, yValue: 81, size: 3, party: "Dem" },
  { name: "Chenango County", xValue: 45, yValue: 80, size: 2, party: "Dem" },
  { name: "Clinton County", xValue: 50, yValue: 75, size: 3, party: "Dem" },
  { name: "Columbia County", xValue: 55, yValue: 82, size: 4, party: "Dem" },
  { name: "Cortland County", xValue: 65, yValue: 67, size: 3, party: "Dem" },
  { name: "Delaware County NY", xValue: 70, yValue: 50, size: 2, party: "Dem" },
  { name: "Oklahoma County", xValue: 90, yValue: 40, size: 8, party: "Rep" },
  { name: "Tulsa County", xValue: 94, yValue: 35, size: 7, party: "Rep" },
  { name: "Cleveland County", xValue: 98, yValue: 42, size: 6, party: "Rep" },
  { name: "Canadian County", xValue: 102, yValue: 50, size: 5, party: "Rep" },
  { name: "Payne County", xValue: 106, yValue: 44, size: 6, party: "Rep" },
  { name: "Comanche County", xValue: 110, yValue: 52, size: 6, party: "Rep" },
  { name: "Pottawatomie County", xValue: 114, yValue: 58, size: 4, party: "Rep" },
  { name: "Grady County", xValue: 118, yValue: 49, size: 5, party: "Rep" },
  { name: "Muskogee County", xValue: 122, yValue: 60, size: 5, party: "Rep" },
  { name: "Garfield County", xValue: 126, yValue: 54, size: 4, party: "Rep" },
  { name: "Rogers County", xValue: 130, yValue: 63, size: 5, party: "Rep" },
  { name: "Wagoner County", xValue: 134, yValue: 68, size: 4, party: "Rep" },
  { name: "Creek County", xValue: 138, yValue: 59, size: 4, party: "Rep" },
  { name: "Le Flore County", xValue: 142, yValue: 70, size: 3, party: "Rep" },
  { name: "Kay County", xValue: 146, yValue: 65, size: 3, party: "Rep" },
  { name: "Stephens County", xValue: 150, yValue: 72, size: 4, party: "Rep" },
  { name: "Adair County", xValue: 154, yValue: 68, size: 3, party: "Rep" },
  { name: "Atoka County", xValue: 158, yValue: 75, size: 2, party: "Rep" },
  { name: "Bryan County", xValue: 162, yValue: 70, size: 4, party: "Rep" },
  { name: "Caddo County", xValue: 166, yValue: 78, size: 3, party: "Rep" },
  { name: "Carter County", xValue: 170, yValue: 72, size: 5, party: "Rep" },
  { name: "Cherokee County", xValue: 100, yValue: 48, size: 4, party: "Rep" },
  { name: "Choctaw County", xValue: 105, yValue: 41, size: 2, party: "Rep" },
  { name: "Cimarron County", xValue: 115, yValue: 55, size: 1, party: "Rep" },
  { name: "Coal County", xValue: 120, yValue: 50, size: 2, party: "Rep" },
];
