version: "3.8"

services:
  db:
    image: postgres:17
    container_name: leffison-db
    ports:
      - "5433:5432" # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - leffison_pg_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
  db-setup:
    build: .
    container_name: db-setup
    restart: "no"
    depends_on:
        [db]
    environment:
      PGUSER: Leffison Members
      PGDATABASE: leffison_db
      PGPASSWORD: raj
      PGPORT: 5432 # The internal port that's exposed.
      PGHOST: db
    entrypoint: ["/project-root/construct-db.sh"]
    volumes:
      - leffison_pg_data:/var/lib/postgresql/data
      - ./sql:/sql-scripts
      - .:/project-root

volumes:
  leffison_pg_data:
