/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface VoterModel {
  voterId?: number;
  firstName?: string;
  lastName?: string;
  dateOfBirth?: string;
  precinct_id?: number;
}

export const getAllVoters = <TData = AxiosResponse<VoterModel[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/voters`,options
    );
  }

export const getVoter = <TData = AxiosResponse<VoterModel>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/voters/${id}`,options
    );
  }

export type GetAllVotersResult = AxiosResponse<VoterModel[]>
export type GetVoterResult = AxiosResponse<VoterModel>
