---
config:
  layout: elk
  look: neo
  theme: neutral
---
sequenceDiagram
  autonumber

  title: GUI-27 - Display Gingles Chart (required)
  actor User as User

  box Frontend
    participant landingPage as landingPage#58;DOMNode
    participant dropDown as dropDown#58;DOMNode
    participant chart as chart#58;DOMNode
    participant Axios as #58;Axios
  end

  box Backend
    participant Controller as #58;Controller
    participant Service as #58;Service
    participant Repository as #58;Repository
  end
  
  Note right of Repository: IStateDAO in codebase

  Note right of User: Visits state/{fipsCode}
  activate landingPage
  User ->>+ landingPage: Click State

  activate dropDown
  landingPage ->> dropDown: Render
  User ->> dropDown: Select 'Ecological Inference' option
  Note left of dropDown: Specifically, the 'Gingles Chart' tab is clicked

  dropDown ->>+ chart: Render

  Note left of Axios: Orval used to generate typesafe request wrappers
  chart ->>+ Axios: getElectionResultsSummary(fipsCode, year=2024)
  chart ->> Axios: getDemographicStatisticsByCounty(fipsCode, countyFipsCode)
  chart ->> Axios: getRegressionCoefficients()

  Note left of Controller: year=2024, is a default query parameter
  Axios ->>+ Controller: GET /state/${fipsCode}/election-year-results/${year}
  Axios ->> Controller: getElectionResultsSummary(fipsCode, year=2024)
  Axios ->> Controller: GET /state/${fipsCode}/${countyFipsCode}/demographic-statistics
  Axios ->> Controller: getDemographicStatisticsByCounty(fipsCode, countyFipsCode)
  Axios ->> Controller: GET /regression-calculation/
  Axios ->> Controller: getRegressionCoefficients()

  Note left of Controller: The Servlet + Jackson Serialization step is omitted for simplicity. <br> The full event flow is in our diagram for GUI-2: Display State
  
  Controller ->>+ Service: getElectionResultsSummary(fipsCode, year=2024)
  Controller ->> Service: getDemographicStatisticsByCounty(fipsCode, countyFipsCode)
  Controller ->> Service: getRegressionCoefficients()

  Service ->>+ Repository: getElectionResultsSummary(fipsCode, year=2024)
  Service ->> Repository: getDemographicStatisticsByCounty(fipsCode, countyFipsCode)
  Service ->> Repository: getRegressionCoefficients()
  
  Note left of Repository: Calls into our custom ORM solution, performing row mapping <br> (simplified, full-flow in GUI-2: Display State)
  Repository -->> Service: List<ElectionResultsSummaryModel>
  Repository -->> Service: DemographicStatisticsModel
  Repository -->>- Service: Map<string, number[]>
  note left of Repository: Regression information is represented as a map where the key represents<br>the demographic and the value is a list of coefficients of the regression line
  
  Service -->> Controller: List<ElectionResultsSummaryModel>
  Service -->> Controller: DemographicStatisticsModel
  Service -->>- Controller: Map<string, number[]>

  Note left of Controller: Serialized into a JSON string
  Controller -->> Axios: HTTP 200 OK: JSONString
  Controller -->> Axios: HTTP 200 OK: JSONString
  Controller -->>- Axios: HTTP 200 OK: JSONString
  Axios -->> chart: List<ElectionResultsSummaryModel>
  Axios -->> chart: DemographicStatisticsModel
  Axios -->>- chart: Map<string, number[]>
  deactivate chart

  Note left of Axios: Each bubble's data is calculated from the server<br>response object and plotted using D3
  Note left of Axios: The non-linear regression line is drawn using D3<br>based on the coefficients in the server response object.<br>We use a quadratic regression model.
  
  deactivate dropDown
  deactivate landingPage
  