---
  config:
    layout: elk
    look: neo
    theme: neutral
---

sequenceDiagram
    autonumber

    title: GUI-3 - Provisional ballot bar chart (required)
    actor User
    box Frontend
        participant LandingPage as LandingPage#58;DOMNode
        participant Chart as Chart#58;DOMNode

        participant Axios as #58;Axios
    end

    box Backend
        participant Controller as #58;Controller
        participant Service as #58;Service
        participant Repository as #58;Repository
    end

    User->>LandingPage: Click State

    activate LandingPage
    LandingPage->>Chart: Render
    activate Chart

    Chart->>Axios: getProvisionalBallots(fipsCode, 2024, true)
    activate Axios
    note right of Axios: JSON string serialized into JS string
    note left of Axios: Call to Axios wrapped by client api library OpenAPI

    Axios->>Controller: GET /state/{fipsCode}/provisional_ballots?aggregate=true
    activate Controller
    note over Controller: Becomes a JSON string from Jackson

    Controller->>Service: getProvisionalBallots(fipsCode, year=2024, aggregate=true)
    activate Service

    Service->>Repository: query(ProvisionalBallotStatisticsModel.Query(), aggregate=true)
    activate Repository
    note right of Repository: Called DAO in codebase

    Repository->>Service: List<ProvisionalBallotStatisticsModel>
    deactivate Repository
    Service->>Controller: List<ProvisionalBallotStatisticsModel>
    deactivate Service
    Controller->>Axios: HTTP 200
    deactivate Controller

    Axios->>Chart: List<ProvisionalBallotStatisticsModel>
    deactivate Axios
    Chart->>LandingPage: Done
    deactivate Chart

    LandingPage->>User: Display
    deactivate LandingPage
  