---
  config:
    layout: elk
    look: neo
    theme: neutral
---

sequenceDiagram
    autonumber

    title: GUI-5 - Provisional ballot choropleth (required)
    actor User
    box Frontend
        participant LandingPage as LandingPage#58;DOMNode
        participant Map as Map#58;DOMNode

        participant Axios as #58;Axios
    end

    box Backend
        participant Controller as #58;Controller
        participant Service as #58;Service
        participant DB as #58;Repository
    end

    note right of DB: IStateDAO in codebase

    User->>LandingPage: Click State
    note left of LandingPage: Visits /state/{fipsCode}

    activate LandingPage
    activate Controller
    LandingPage->>Map: Render
    activate Map

    Map->>Axios: getProvisionalBallots(fipsCode, 2024, false)
    note left of Axios: We use Orval to generate typesafe request wrappers
    activate Axios

    Axios->>Controller: GET /state/{fipsCode}/provisional_ballots?aggregate=false
    Axios->>Controller: getProvisionalBallots(fipsCode, year=2024, aggregate=false)
    note left of Controller: year=2024, is a default query parameter
    
    note left of Controller: For simplicity, we are omitting the Servlet + Jackson Serialization<br/>step, the full-flow of events is shown in the diagram for GUI-2: Display State.
    activate Service
    activate DB
    Controller->>Service: getProvisionalBallots(fipsCode, year=2024, aggregate=false)

    Service->>DB: getProvisionalBallots(fipsCode, year=2024, aggregate=false)
    note left of DB: Calls into our custom ORM solution, performing row mapping<br/>(simplified, full-flow in GUI-2: Display State).
    DB-->>Service: List<ProvisionalBallotStatisticsModel>
    Service-->>Controller: List<ProvisionalBallotStatisticsModel>
    deactivate Service
    deactivate DB
    note left of Controller: Would be serialized into a JSON string

    Controller-->>Axios: HTTP 200 OK: JSONString
    deactivate Axios

    Axios-->>Map: List<ProvisionalBallotStatisticsModel>
    note left of Map: Using Styling function to color map based off<br/>ratio calculated from return values.
    deactivate Map
    deactivate Controller
    deactivate LandingPage