const ID_SELECTION_PROVISIONAL_BALLOT = 0;
const ID_SELECTION_ACTIVE_VOTERS = 1;
const ID_SELECTION_POLLBOOK_DELETION = 2;
const ID_SELECTION_MAIL_BALLOT_REJECTIONS = 3;
const ID_SELECTION_COMPARE_VOTER_REGISTRATION_RATES = 10;

const ID_SELECTION_VOTING_EQUIPMENT_BY_TYPE = 4;
const ID_SELECTION_VOTING_EQUIPMENT_BY_AGE = 5;
const ID_SELECTION_VOTING_EQUIPMENT_SUMMARY = 16;

const ID_SELECTION_REJECTED_BALLOTS = 6;
const ID_SELECTION_MAIL_IN_VOTING = 7;

const ID_SELECTION_VOTER_REGISTRATION = 8;
const ID_SELECTION_VOTER_REGISTRATION_SHOW_VOTER_TABLE = 9;
const ID_SELECTION_VIEW_CVAP_INFO = 11;
const ID_SELECTION_VIEW_CVAP_PERCENTAGE = 12;

const ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_GINGLES_CHART = 13;
const ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_VOTING_EQUIPMENT = 14;
const ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_REJECTED_BALLOTS = 15;

export {
  ID_SELECTION_PROVISIONAL_BALLOT,
  ID_SELECTION_ACTIVE_VOTERS,
  ID_SELECTION_POLLBOOK_DELETION,
  ID_SELECTION_MAIL_BALLOT_REJECTIONS,
  ID_SELECTION_COMPARE_VOTER_REGISTRATION_RATES,
  ID_SELECTION_VOTING_EQUIPMENT_BY_AGE,
  ID_SELECTION_VOTING_EQUIPMENT_BY_TYPE,
  ID_SELECTION_VOTING_EQUIPMENT_SUMMARY,
  ID_SELECTION_REJECTED_BALLOTS,
  ID_SELECTION_MAIL_IN_VOTING,
  ID_SELECTION_VOTER_REGISTRATION,
  ID_SELECTION_VOTER_REGISTRATION_SHOW_VOTER_TABLE,
  ID_SELECTION_VIEW_CVAP_INFO,
  ID_SELECTION_VIEW_CVAP_PERCENTAGE,
  ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_GINGLES_CHART,
  ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_REJECTED_BALLOTS,
  ID_SELECTION_VIEW_ECOLOGICAL_INFERENCE_VOTING_EQUIPMENT,
};
