---
  config:
    class:
      hideEmptyMembersBox: true
    layout: elk
    look: neo
    theme: light
---
%% mmdc --width 2560 --height 1080 --theme neutral -o class-diagram.svg -i mono.mermaid

classDiagram
direction BT
namespace Models {
    class ProvisionalBallotStatisticsModel {
        <<SqlQueryable(collection="app.eavs_data")>>
        +fullRegionId: string
        +countyName: string
        +totalBallotsCast: int
        +ballotReasonNotOnList: int
        +ballotReasonNoIdAvailable: int
        +ballotReasonChallengedByOfficial: int
        +ballotReasonChallengedByOther: int
        +ballotReasonWrongPrecinct: int
        +ballotReasonNotUpdatedAddress: int
        +ballotReasonDidNotSurrender: int
        +ballotReasonExtendedVotingHours: int
        +ballotReasonSameDayRegistration: int
        +ballotReasonOther: int
        +Queryable() AutoSqlQueryable~~
    }
    class VoterRegistrationStatisticsModel {
        <<SqlQueryable(collection="app.eavs_data")>>
        +fullRegionId: string
        +countyName: string
        +total: int
        +active: int
        +inactive: int
        +Queryable() AutoSqlQueryable~~
    }
    class PollbookDeletionStatisticsModel {
        <<SqlQueryable(collection="app.eavs_data")>>
        +fullRegionId: string
        +countyName: string
        +totalRemoved: int
        +removedReasonMoved: int
        +removedReasonDeceased: int
        +removedReasonFelony: int
        +removedReasonFailedToConfirm: int
        +removedReasonIncompetent: int
        +removedReasonRequested: int
        +removedReasonDuplicate: int
        +removedOther: int
        +Queryable() AutoSqlQueryable~~
    }
    class MailBallotRejectionStatisticsModel {
        <<SqlQueryable(collection="app.eavs_data")>>
        +fullRegionId: string
        +countyName: string
        +rejectTotal: int
        +rejectLate: int
        +rejectNoSignature: int
        +rejectNoWitnessSignature: int
        +rejectSignatureMismatch: int
        +rejectUnofficialEnv: int
        +rejectBallotMissing: int
        +rejectNoSecrecyEnvironment: int
        +rejectMultipleInEnvironment: int
        +rejectUnsealedEnvironment: int
        +rejectNoPostMark: int
        +rejectNoAddress: int
        +rejectVoterDeceased: int
        +rejectDuplicateVote: int
        +rejectMissingDocumentation: int
        +rejectNotEligible: int
        +rejectNoApplication: int
        +rejectOther: int
        +Queryable() AutoSqlQueryable~~
    }
    class BallotStatisticsModel {
        <<SqlQueryable(view="app.v_state_year_summary")>>
        +fullRegionId: string
        +regionName: string
        +dropboxBallots: int
        +totalBallotsCast: int
        +Queryable() AutoSqlQueryable~~
    }
    class ViewStateYearSummaryModel {
        <<SqlQueryable(view="app.v_state_year_summary")>>
        +stateFipsCode: int
        +stateCode: string
        +stateName: string
        +forYear: int
        +activeRegistered: int
        +inactiveRegistered: int
        +totalRegistered: int
        +totalBallotsCast: int
        +earlyVotingTotal: int
        +ballotsByMail: int
        +totalProvisionalBallotsCast: int
        +activeVoterRate: double
        +inactiveVoterRate: double
        +turnOutRate: double
        +earlyVotingShareRate: double
        +mailinBallotVotingShareRate: double
        +Queryable() AutoSqlQueryable~~
    }
    class StateInformationDataRowModel {
        <<SqlQueryable(view="app.states")>>
        +state_id: int
        +name: string
        +code: string
        +registration_method: string
        +felony_disenfranchisement: int
        +population_total: int
        +citizens_of_voting_age_population: int
        +house_seats_rep: int
        +house_seats_dem: int
        +redistricting_control: string
        +dominant_party: string
        +Queryable() AutoSqlQueryable~~
    }
    class StateInformationModel {
        +fipsCode: string
        +name: string
        +registrationMethod: RegistrationMethod
        +felonyDisenfranchisement: FelonyDisenfranchisement
        +populationTotal: int
        +cvapTotal: int
        +affiliation: PoliticalParty

        +fromRaw(rowModel: StateInformationDataRowModel): StateInformationModel
    }
    class GeoUnitCentroidModel {
        +fullRegionId: string
        +countyName: string
        +centerX: float
        +centerY: float
    }
    class VotingEquipmentModel {
        +manufacturer: string
        +equipmentType: string
        +modelName: string
        +discontinued: boolean?
        +firstManufactured: int?
        +lastManufactured: int?
        +operatingSystem: string?
        +firmwareVersion: string?
        +vvpat: boolean?
        +certificationLevel: string?
        +securityRiskDescription: string?
    }
    class VoterRegistrationDataModel {
        <<SqlQueryable(view="app.voter_registration")>>
        +regionId: string
        +firstName: string
        +middleName: string
        +lastName: string
        +partyAffiliation: string
        +status: string
        +Queryable() AutoSqlQueryable~~
    }
    class CollectionSortParamFieldModel {
        +field: string
        +sort: string
    }
    class CollectionSortParamModel {
        +fields: CollectionSortParamFieldModel[]
    }
    class ElectionResultsSummaryModel {
        <<SqlQueryable(collection="app.election_results")>>
        +fullRegionId: string,
        +regionName: string,
        +republicanVotes: int,
        +democratVotes: int,
        +otherVotes: int,
        +totalVotes: int
        +Queryable() AutoSqlQueryable~~
    }
    class VotingEquipmentUsageStatisticsEntryModel {
        <<SqlQueryable(collection="app.equipment_usage")>>
        +stateName: string,
        +stateId: int,
        +deviceType: string,
        +certification: string,
        +uniqueModels: string,
        +totalDevices: int,
    }
    class VotingEquipmentUsageStatisticsModel {
        +stateName: string,
        +stateId: int,
        +dreNoVvpatTotal: int,
        +dreVvpatTotal: int,
        +bmdTotal: int,
        +scannerTotal: int,

        +fromDataRows(rows: VotingEquipmentUsageStatisticsEntryModel[])
    }
    class GeoJSON {
        refer to official GeoJSON documentation for schema.
    }
}

namespace Controllers {
    class StateController {
        <<RequestMapping("/state")>>
        +GET /$fipsCode/geometry(fipsCode: string) GeoJSON?
        +GET /$fipsCode/centroids(fipsCode: string) Dictionary~string, GeoUnitCentroidModel~

        +GET /$fipsCode/provisional-ballots(fipsCode: string, year: int, aggregate: boolean) ProvisionalBallotStatisticsModel[]
        +GET /$fipsCode/$countyFipsCode/provisional-ballots(fipsCode: string, countyFipsCode: string, year: int, aggregate: boolean) ProvisionalBallotStatisticsModel?
        
        +GET /$fipsCode/voter-registration-count(fipsCode: string, year: int, aggregate: boolean) VoterRegistrationStatisticsModel[]
        +GET /$fipsCode/$countyFipsCode/voter-registration-count(fipsCode: string, countyFipsCode: string, year: int, aggregate: boolean) VoterRegistrationStatisticsModel?

        +GET /$fipsCode/pollbook-deletions(fipsCode: string, year: int, aggregate: boolean) PollbookDeletionStatisticsModel[]
        +GET /$fipsCode/$countyFipsCode/pollbook-deletions(fipsCode: string, year: int) PollbookDeletionStatisticsModel?

        +GET /$fipsCode/mail-ballot-rejections(fipsCode: string, year: int, aggregate: boolean) MailBallotRejectionStatisticsModel[]
        +GET /$fipsCode/$countyFipsCode/mail-ballot-rejections(fipsCode: string, year: int) MailBallotRejectionStatisticsModel?
        
        +GET /$fipsCode/ballot-statistics(fipsCode: string, year: int, aggregate: boolean) BallotStatisticsModel[]
        +GET /$fipsCode/$countyFipsCode/ballot-statistics(fipsCode: string, year: int) BallotStatisticsModel?

        +GET /$fipsCode/election-year-results/$year(fipsCode: string, year: int, inAggregate: bolean) ElectionResultsSummaryModel[]

        +GET /$fipsCode/year-summary(fipsCode: string) ViewStateYearSummaryModel[]
        +GET /$fipsCode/year-summary/$year(fipsCode: string, year: int) ViewStateYearSummaryModel?
    }

    class VoterRegistrationController {
        <<RequestMapping("/voter-registration")>>

        +GET /(stateFips: string, countyFips: string, pageSize: int, pageIndex: int, party: partySelectionFilterId, encodedSortParams: string) VoterRegistrationDataModel[]
        +GET /count(stateFips: string, countyFips: string, partySelectionFilterId: int) int
    }

    class VoterEquipmentController {
        <<RequestMapping("/votingequipment")>>
        +GET /by-manufacturer/$manufacturer(manufacturer: string) VotingEquipmentModel[]
        +GET /by-type/$type(type: string) VotingEquipmentModel[]
        +GET /$manufacturer/$model(manufacturer: string, model: string) VotingEquipmentModel?
    }
}

namespace Services {
    class StateService {
        <<Service>>
        /* All methods are cached except for getBoundaryGeometry, which is too large in my opinion to cache. */
        - dao: IStateDAO;
        + getBoundaryGeometry(fipsCode: string) GeoJSON?;

        + getProvisionalBallotDataForCounty(fipsCode: string, countyCode: string, year: int) ProvisionalBallotStatisticsModel?;
        + getProvisionalBallotData(fipsCode: string, year: int, inAggregate: bool) ProvisionalBallotStatisticsModel[];


        + getVoterRegistrationDataForCounty(fipsCode: string, countyCode: string, year: int) VoterRegistrationStatisticsModel?;
        + getVoterRegistrationData(fipsCode: string, year: int, inAggregate: bool) VoterRegistrationStatisticsModel[];

        
        + getPollbookDeletionDataForCounty(fipsCode: string, countyCode: string, year: int) PollbookDeletionStatisticsModel?;
        + getPollbookDeletionData(fipsCode: string, year: int, inAggregate: bool) PollbookDeletionStatisticsModel[];


        + getMailBallotRejectionDataForCounty(fipsCode: string, countyCode: string, year: int) MailBallotRejectionStatisticsModel?;
        + getMailBallotRejectionData(fipsCode: string, year: int, inAggregate: bool) MailBallotRejectionStatisticsModel[];

        + getBallotStatistics(fipsCode: string, year: int) BallotStatisticsModel?;
        + getBallotStatisticsForCounty(fipsCode: string, countyFipsCode: string, year: int) BallotStatisticsModel[];

        + getViewStateYearSummaryDataByYear(fipsCode: string, year: int) ViewStateYearSummaryModel?;
        + getViewStateYearSummaryData(fipsCode: string) ViewStateYearSummaryModel[];

        + getElectionResultsSummaryDataForState(fipsCode: string, year: int, aggregated: boolean) ElectionResultsSummaryModel[]

        + getCountyGeoUnitCentroids(fipsCode: string) Dictionary~string, GeoUnitCentroidModel~;
        + getStateInformationTable() Dictionary~string, StateInformationModel~;
    }

    class VoterEquipmentService {
        <<Service>>
        -dao: IVoterEquipmentDAO;
        +getAllVotingEquipment() VotingEquipmentModel[];
        +getAllVotingEquipmentByManufacturer(manufacturer: string) VotingEquipmentModel[];
        +getAllVotingEquipmentByType(type: string) VotingEquipmentModel[];
        +getVotingEquipment(manufacturer: string, model: string) VotingEquipmentModel?;
        +getVotingEquipmentUsage(fipsCode: string) VotingEquipmentUsageStatisticsModel
    }

    class VoterRegistrationService {
        <<Service>>
        - dao: IVoterRegistrationDAO;
        + getDetailedVoterRegistrationData(stateFips: string, countyFips: string?, pageSize: int, pageIndex: int, sortingParams: CollectionSortParamModel?, partySelectionFilterId: int) VoterRegistrationDataModel[]
        + getDetailedVoterRegistrationDataCount(stateFips: string, countyFips: string?, partySelectionFilterId: int) int
    }
}

namespace DataAccessObject {
    class IVoterRegistrationDAO {
        +getDetailedVoterRegistrationDataRows(stateFips: string, countyFips: string?, pageSize: int, pageIndex: int, sortingParams: CollectionSortParamModel?, partySelectionFilterId: int) VoterRegistrationDataModel[]
        +getDetailedVoterRegistrationDataCount(stateFips: string, countyFips: string?, partySelectionFilterId: int)
    }

    class VoterRegistrationDAO {
        -logger: Logger
        -jdbcTemplate: JdbcTemplate

        -getFilterClauseForPartySelection(partySelectionFilterId: int) string
    }

    class IVoterEquipmentDAO {
        <<Interface>>
        +getAllVotingEquipment() VotingEquipmentModel[]
        +getVotingEquipmentByType(type: string) VotingEquipmentModel[]
        +getVotingEquipmentByManufacturer(manufacturer: string) VotingEquipmentModel[]
        +getVotingEquipmentUsage(fipsCode: string) VotingEquipmentUsageStatisticsModel[]
        +getVotingEquipmentModel(manufacturer: string, model: string) VotingEquipmentModel?
    }

    class VoterEquipmentDAO {
        -logger: Logger
        -jdbcTemplate: JdbcTemplate
    }

    class IStateDAO {
        <<Interface>>
        +getGeometryBoundary(fipsCode: string) Optional~GeoJSON~

        +getProvisionBallotRows(fipsCode: string, year: int, aggregate: boolean) ProvisionalBallotStatisticsModel[]
        +getProvisionBallotRowByCounty(fipsCode: string, countyCode: string, year: int) ProvisionalBallotStatisticsModel?

        +getVoterRegistrationRows(fipsCode: string, year: int, aggregate: boolean) VoterRegistrationStatisticsModel[]
        +getVoterRegistrationRowByCounty(fipsCode: string, year: int) VoterRegistrationStatisticsModel?
        
        +getPollbookDeletionRows(fipsCode: string, year: int, aggregate: boolean) PollbookDeletionStatisticsModel[]
        +getPollbookDeletionRowByCounty(fipsCode: string, year: int) PollbookDeletionStatisticsModel?

        +getMailBallotRejectionRows(fipsCode: string, year: int, aggregate: boolean) MailBallotRejectionStatisticsModel[]
        +getMailBallotRejectionRowByCounty(fipsCode: string, year: int) MailBallotRejectionStatisticsModel?

        +getBallotStatisticsRows(fipsCode: string, year: int) BallotStatisticsModel[]
        +getBallotStatisticsRowByCounty(fipsCode: string, countyCode: string, year: int) BallotStatisticsModel?

        +getStateYearSummaryRows(fipsCode: string) ViewStateYearSummaryModel[]
        +getStateYearSummaryRowByYear(fipsCode: string, year: int) ViewStateYearSummaryModel?

        +getStateElectionResults(fipsCode: string, year: int, aggregated: boolean) ElectionResultsSummaryModel;
        +getStateInformationDataRowModels() StateInformationDataRowModel[]

        +getGeoUnitCentroids(fipsCode: string) Dictionary~FipsCode, GeoUnitCentroidModel~
    }

    class StateDAO {
        -logger: Logger
        -preprocessedGeospatialPath: Path
        -localCountyCentroidsCsvDataPath: Path
        -geoUnitCentroidMap: Dictionary~string, GeoUnitCentroidModel~
        -jdbcTemplate: JdbcTemplate

        -getStateDataRows(type: Class~T~, fipsCode:string, year:int, aggregated:boolean) List~T~
        -populateGeoUnitCentroidTable()
    }
}
namespace Helpers {
    class AutoSqlQueryable~T~ {
        +Mapper() RowMapper~T~
        +QueryView() string
        +Query(asSumAggregate: boolean) string
        +QueryOrdering(sortParams: CollectionSortParamModel?)
    }

    class SqlQueryableInvocationHandler {
        -visitField(resultSet: ResultSet, field: Field, columnNumber: int) Object
        -visitType(resultSet: ResultSet, type: Type, columnNumber: int) Object
        -firstMatchingArityConstructor(constructors: Constructor[], targetArity: int) Constructor
        +invoke(proxy: Object, method: Method, args: Object[]) Object
    }
}

AutoSqlQueryable "1" *-- "1" SqlQueryableInvocationHandler : contains
note for SqlQueryableInvocationHandler "Internal class used to map rows<br/>on JDBC ResultSets"
namespace Enums {
    class FelonyDisenfranchisement {
        <<enum>>
        UNKNOWN = 0
        NO_DENIAL_OF_VOTING = 1
        RESTORATION_UPON_RELEASE_FROM_PRISON = 2
        RESTORATION_AFTER_PAROLE_AND_PROBATION = 3
        ADDITIONAL_ACTION_FOR_RESTORATION = 4
    }
    class PoliticalParty {
        <<enum>>
        UNAFFILIATED,
        DEMOCRAT = 'D'
        REPUBLICAN = 'R'
    }
    class RegistrationMethod {
        NONE=0,
        OPT-IN = "opt-in",
        OPT-OUT = "opt-out",
    }
}

%% relationships
VoterRegistrationDAO <|-- IVoterRegistrationDAO : Implements
VoterEquipmentDAO <|-- IVoterEquipmentDAO : Implements
StateDAO <|-- IStateDAO : Implements

CollectionSortParamFieldModel <-- CollectionSortParamModel : Has
AutoSqlQueryable <-- ElectionResultsSummaryModel : Has
AutoSqlQueryable <-- ProvisionalBallotStatisticsModel : Has
AutoSqlQueryable <-- VoterRegistrationStatisticsModel : Has
AutoSqlQueryable <-- PollbookDeletionStatisticsModel : Has
AutoSqlQueryable <-- MailBallotRejectionStatisticsModel : Has
AutoSqlQueryable <-- BallotStatisticsModel : Has
AutoSqlQueryable <-- ViewStateYearSummaryModel : Has
AutoSqlQueryable <-- StateInformationDataRowModel : Has
AutoSqlQueryable <-- VoterRegistrationDataModel : Has

StateInformationModel <-- StateInformationDataRowModel : ConvertedInto

StateService <-- IStateDAO : Has
VoterEquipmentService <-- IVoterEquipmentDAO : Has
VoterRegistrationService <-- IVoterRegistrationDAO : Has

StateController <-- StateService : Uses
VoterEquipmentController <-- VoterEquipmentService : Uses
VoterRegistrationController <-- VoterRegistrationService : Uses
